import * as c from "viem/chains";

export default [
  // ── Mainnets (by popularity / TVL) ──
  {
    chain: c.mainnet,
    color: "#627EEA",
    icon: "ethereum",
    alchemy: "eth-mainnet",
    trust: "ethereum",
  },
  { chain: c.bsc, color: "#F0B90B", icon: "binance-smart-chain", trust: "smartchain" },
  {
    chain: c.arbitrum,
    color: "#28A0F0",
    icon: "arbitrum-one",
    alchemy: "arb-mainnet",
    trust: "arbitrum",
  },
  { chain: c.base, color: "#0052FF", icon: "base", alchemy: "base-mainnet", trust: "base" },
  {
    chain: c.polygon,
    color: "#8247E5",
    icon: "polygon",
    alchemy: "polygon-mainnet",
    trust: "polygon",
  },
  {
    chain: c.optimism,
    color: "#FF0420",
    icon: "optimism",
    alchemy: "opt-mainnet",
    trust: "optimism",
  },
  {
    chain: c.avalanche,
    color: "#E84142",
    icon: "avalanche",
    alchemy: "avax-mainnet",
    trust: "avalanchec",
  },
  { chain: c.blast, color: "#FCFC03", icon: "blast", alchemy: "blast-mainnet" },
  { chain: c.linea, color: "#61DFFF", icon: "linea", alchemy: "linea-mainnet" },
  { chain: c.scroll, color: "#FFEEDA", icon: "scroll", alchemy: "scroll-mainnet" },
  { chain: c.zkSync, color: "#8C8DFC", icon: "zksync", alchemy: "zksync-mainnet", trust: "zksync" },
  { chain: c.manta, color: "#15B5E0", icon: "manta-pacific" },
  { chain: c.mantle, color: "#000000", icon: "mantle", alchemy: "mantle-mainnet" },
  { chain: c.celo, color: "#FCFF52", icon: "celo", alchemy: "celo-mainnet" },
  { chain: c.gnosis, color: "#04795B", icon: "gnosis", alchemy: "gnosis-mainnet", trust: "xdai" },
  { chain: c.fantom, color: "#1969FF", icon: "fantom", alchemy: "fantom-mainnet", trust: "fantom" },
  {
    chain: c.polygonZkEvm,
    color: "#7B3FE4",
    icon: "polygon-zkevm",
    alchemy: "polygonzkevm-mainnet",
  },
  { chain: c.moonbeam, color: "#53CBC8", icon: "moonbeam", alchemy: "moonbeam-mainnet" },
  { chain: c.moonriver, color: "#F2B705", icon: "moonriver" },
  { chain: c.aurora, color: "#70D44B", icon: "aurora" },
  { chain: c.cronos, color: "#002D74", icon: "cronos" },
  { chain: c.metis, color: "#00DACC", icon: "metis-andromeda" },
  { chain: c.zora, color: "#2B5DF0", icon: "zora" },
  { chain: c.mode, color: "#DFFE00", icon: "mode" },
  { chain: c.fraxtal, color: "#000000", icon: "fraxtal" },
  { chain: c.kava, color: "#FF564F", icon: "kava" },
  { chain: c.coreDao, color: "#FF9211" },
  { chain: c.harmonyOne, color: "#00ADE8", icon: "harmony" },
  { chain: c.klaytn, color: "#FE3300", icon: "kaia" },
  { chain: c.filecoin, color: "#0090FF", icon: "filecoin" },
  { chain: c.fuse, color: "#B4F9BA", icon: "fuse" },
  { chain: c.iotex, color: "#00D4AA" },
  { chain: c.rootstock, color: "#FF914D", icon: "rootstock" },
  { chain: c.telos, color: "#571AFF", icon: "telos" },
  { chain: c.boba, color: "#CCFF00", icon: "boba" },
  { chain: c.flare, color: "#E42058", icon: "flare" },
  { chain: c.wemix, color: "#6046FF" },
  { chain: c.astar, color: "#0070EB", alchemy: "astar-mainnet" },
  { chain: c.arbitrumNova, color: "#E57310", icon: "arbitrum-nova" },
  { chain: c.apeChain, color: "#0054FA", icon: "apechain" },
  { chain: c.worldchain, color: "#000000", icon: "world" },
  { chain: c.bob, color: "#F25E31", icon: "bob" },
  { chain: c.lisk, color: "#4070F4", icon: "lisk" },
  { chain: c.redstone, color: "#F34242" },
  { chain: c.sei, color: "#9B1B2E", icon: "sei-network" },
  { chain: c.taiko, color: "#E81899", icon: "taiko" },
  { chain: c.berachain, color: "#7C3503" },
  { chain: c.abstract, color: "#1D1D1B", icon: "abstract" },
  { chain: c.ink, color: "#7C5CFF", icon: "ink" },
  { chain: c.hemi, color: "#FF6B35", icon: "hemi" },
  // ── Testnets (same order as parent mainnet) ──
  { chain: c.sepolia, icon: "ethereum", alchemy: "eth-sepolia" },
  { chain: c.bscTestnet, icon: "binance-smart-chain" },
  { chain: c.arbitrumSepolia, icon: "arbitrum-one", alchemy: "arb-sepolia" },
  { chain: c.baseSepolia, icon: "base", alchemy: "base-sepolia" },
  { chain: c.polygonAmoy, icon: "polygon", alchemy: "polygon-amoy" },
  { chain: c.optimismSepolia, icon: "optimism", alchemy: "opt-sepolia" },
  { chain: c.avalancheFuji, icon: "avalanche", alchemy: "avax-fuji" },
  { chain: c.blastSepolia, icon: "blast", alchemy: "blast-sepolia" },
  { chain: c.lineaSepolia, icon: "linea", alchemy: "linea-sepolia" },
  { chain: c.scrollSepolia, icon: "scroll", alchemy: "scroll-sepolia" },
  { chain: c.mantleSepoliaTestnet, icon: "mantle" },
  { chain: c.celoAlfajores, icon: "celo" },
  { chain: c.gnosisChiado },
  { chain: c.fantomTestnet, icon: "fantom" },
  { chain: c.moonbaseAlpha, icon: "moonbase-alpha" },
  { chain: c.cronosTestnet, icon: "cronos" },
  { chain: c.zoraSepolia, icon: "zora" },
  { chain: c.modeTestnet, icon: "mode" },
  { chain: c.fraxtalTestnet, icon: "fraxtal" },
  { chain: c.kavaTestnet, icon: "kava" },
  { chain: c.klaytnBaobab, icon: "kaia" },
  { chain: c.filecoinCalibration, icon: "filecoin" },
  { chain: c.iotexTestnet },
  { chain: c.rootstockTestnet },
  { chain: c.telosTestnet, icon: "telos" },
  { chain: c.bobaSepolia, icon: "boba" },
  { chain: c.flareTestnet, icon: "flare" },
  { chain: c.wemixTestnet },
  { chain: c.bobSepolia, icon: "bob" },
  { chain: c.liskSepolia, icon: "lisk" },
  { chain: c.worldchainSepolia, icon: "world" },
  { chain: c.seiTestnet, icon: "sei-network" },
  { chain: c.taikoHekla, icon: "taiko" },
  { chain: c.berachainBepolia },
  { chain: c.abstractTestnet, icon: "abstract" },
  { chain: c.inkSepolia, icon: "ink" },
  { chain: c.hemiSepolia, icon: "hemi" },
  // ── Local dev ──
  { chain: { ...c.hardhat, testnet: true } },
] satisfies {
  chain: import("viem").Chain;
  color?: string;
  icon?: string;
  alchemy?: string;
  trust?: string;
}[];
