name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - uses: arduino/setup-task@v2
        with:
          version: 3.x

      - run: pnpm install --frozen-lockfile

      - run: task gen
      - run: task typecheck
      - run: task lint
